services:
  
  postgres:
    image: postgres
    container_name: postgres-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n-app
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - n8n-network 

volumes:
  postgres_data:
  n8n_data:

networks:
  n8n-network:
    driver: bridge